### ISSUE TITLE
[ ERROR ] Calling method 'close' of listener 'ListenerV2' failed: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Prates23** [kriffx/robotframework-xray#2]
Hi,

Has already discussed in a meeting between JM and DBservices we have an error which is in the tilte that keeps appearing. In attachment I send the logs. Can you clarify why this error is ocurring? Thank you
[abddservice_clean.log]()

**Comment by kriffx** [comment]
Hello, thank you for opening an issue, I will work to identify this problem, I also removed the file added to your issue because it contains sensitive data, but I already have a copy to analyze.
